# Generated by Django 5.1.4 on 2024-12-29 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_recipient_sender_feedback_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='package',
            field=models.ForeignKey(default=1, help_text='The package associated with this recipient.', on_delete=django.db.models.deletion.CASCADE, related_name='recipient_package', to='packages.package', verbose_name='Package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sender',
            name='package',
            field=models.ForeignKey(default=1, help_text='The package associated with this sender.', on_delete=django.db.models.deletion.CASCADE, related_name='sender_package', to='packages.package', verbose_name='Package'),
            preserve_default=False,
        ),
    ]
