# Generated by Django 5.1.4 on 2024-12-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_recipient_package_sender_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='title',
            field=models.CharField(default='', help_text='Title of the package.', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Dimensions of the package: length or width or height in cm.', max_length=255, null=True, verbose_name='Dimensions'),
        ),
    ]
