# Generated by Django 5.1.4 on 2024-12-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_title_alter_package_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tax_fees',
        ),
    ]
