# Generated by Django 5.1.4 on 2024-12-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_remove_payment_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='customs_declaration',
        ),
        migrations.RemoveField(
            model_name='package',
            name='insurance_coverage',
        ),
        migrations.RemoveField(
            model_name='package',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='package',
            name='value',
        ),
    ]
