# Generated by Django 5.1.4 on 2024-12-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_receiving_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='sender',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient_payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', help_text='Payment status for the recipient.', max_length=10, verbose_name='Recipient Payment Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', help_text='Payment status for the sender.', max_length=10, verbose_name='Sender Payment Status'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
