# Generated by Django 5.1.4 on 2024-12-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingupdate',
            name='delivery_proof_document',
        ),
        migrations.RemoveField(
            model_name='trackingupdate',
            name='delivery_route',
        ),
        migrations.RemoveField(
            model_name='trackingupdate',
            name='package_handling_notes',
        ),
    ]
