# Generated by Django 5.1.4 on 2025-01-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='footer_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
