# Generated by Django 5.1.4 on 2025-01-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_information_footer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='footer_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
